// <auto-generated />
using System;
using Employee_Salary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee_Salary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251224095448_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Employee_Salary.Models.Designation", b =>
                {
                    b.Property<string>("DesignationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesignationID");

                    b.ToTable("Designation");

                    b.HasData(
                        new
                        {
                            DesignationID = "DC",
                            DesignationName = "Document Controller"
                        },
                        new
                        {
                            DesignationID = "PM",
                            DesignationName = "Project Manager"
                        });
                });

            modelBuilder.Entity("Employee_Salary.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DesignationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DesignationID");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmployeeID = "abc",
                            DesignationID = "DC",
                            EName = "abcemployee"
                        },
                        new
                        {
                            EmployeeID = "def",
                            DesignationID = "PM",
                            EName = "defemployee"
                        });
                });

            modelBuilder.Entity("Employee_Salary.Models.LoginUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("LoginUser");

                    b.HasData(
                        new
                        {
                            UserId = "abc",
                            Password = "abc123"
                        },
                        new
                        {
                            UserId = "def",
                            Password = "def123"
                        });
                });

            modelBuilder.Entity("Employee_Salary.Models.SalaryAdjustment", b =>
                {
                    b.Property<int>("Docno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Docno"));

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SalaryIncrement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("WEF")
                        .HasColumnType("datetime2");

                    b.HasKey("Docno");

                    b.HasIndex("EmployeeID");

                    b.ToTable("SalaryAdjustments");

                    b.HasData(
                        new
                        {
                            Docno = 1,
                            EmployeeID = "abc",
                            SalaryIncrement = 5000m,
                            WEF = new DateTime(1900, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Docno = 2,
                            EmployeeID = "abc",
                            SalaryIncrement = 3000m,
                            WEF = new DateTime(1900, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Docno = 3,
                            EmployeeID = "abc",
                            SalaryIncrement = 4000m,
                            WEF = new DateTime(1900, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Docno = 4,
                            EmployeeID = "abc",
                            SalaryIncrement = 2500m,
                            WEF = new DateTime(1901, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Docno = 5,
                            EmployeeID = "abc",
                            SalaryIncrement = 3500m,
                            WEF = new DateTime(1901, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Docno = 6,
                            EmployeeID = "abc",
                            SalaryIncrement = 6000m,
                            WEF = new DateTime(1901, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Docno = 7,
                            EmployeeID = "abc",
                            SalaryIncrement = 4500m,
                            WEF = new DateTime(1901, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Docno = 8,
                            EmployeeID = "abc",
                            SalaryIncrement = 5500m,
                            WEF = new DateTime(1901, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Docno = 9,
                            EmployeeID = "abc",
                            SalaryIncrement = 7000m,
                            WEF = new DateTime(1901, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Docno = 10,
                            EmployeeID = "abc",
                            SalaryIncrement = 8000m,
                            WEF = new DateTime(1901, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Employee_Salary.Models.SalaryApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ApprovedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Docno")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Docno");

                    b.HasIndex("EmployeeID");

                    b.ToTable("SalaryApproval");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovedBy = "def",
                            ApprovedOn = new DateTime(1900, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Docno = 1,
                            EmployeeID = "abc"
                        },
                        new
                        {
                            Id = 2,
                            ApprovedBy = "def",
                            ApprovedOn = new DateTime(1900, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Docno = 2,
                            EmployeeID = "abc"
                        },
                        new
                        {
                            Id = 3,
                            ApprovedBy = "def",
                            ApprovedOn = new DateTime(1900, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Docno = 3,
                            EmployeeID = "abc"
                        },
                        new
                        {
                            Id = 4,
                            ApprovedBy = "def",
                            ApprovedOn = new DateTime(1901, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Docno = 4,
                            EmployeeID = "abc"
                        },
                        new
                        {
                            Id = 5,
                            ApprovedBy = "def",
                            ApprovedOn = new DateTime(1901, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Docno = 5,
                            EmployeeID = "abc"
                        },
                        new
                        {
                            Id = 6,
                            ApprovedBy = "def",
                            ApprovedOn = new DateTime(1901, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Docno = 6,
                            EmployeeID = "abc"
                        },
                        new
                        {
                            Id = 7,
                            ApprovedBy = "def",
                            ApprovedOn = new DateTime(1901, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Docno = 7,
                            EmployeeID = "abc"
                        },
                        new
                        {
                            Id = 8,
                            ApprovedBy = "def",
                            ApprovedOn = new DateTime(1901, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Docno = 8,
                            EmployeeID = "abc"
                        },
                        new
                        {
                            Id = 9,
                            ApprovedBy = "def",
                            ApprovedOn = new DateTime(1901, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Docno = 9,
                            EmployeeID = "abc"
                        },
                        new
                        {
                            Id = 10,
                            ApprovedBy = "def",
                            ApprovedOn = new DateTime(1901, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Docno = 10,
                            EmployeeID = "abc"
                        });
                });

            modelBuilder.Entity("Employee_Salary.Models.Employee", b =>
                {
                    b.HasOne("Employee_Salary.Models.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Designation");
                });

            modelBuilder.Entity("Employee_Salary.Models.SalaryAdjustment", b =>
                {
                    b.HasOne("Employee_Salary.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Employee_Salary.Models.SalaryApproval", b =>
                {
                    b.HasOne("Employee_Salary.Models.SalaryAdjustment", "SalaryAdjustment")
                        .WithMany()
                        .HasForeignKey("Docno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee_Salary.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("SalaryAdjustment");
                });
#pragma warning restore 612, 618
        }
    }
}
